import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {readTimingArchive} from './reference-timing';
import {candidateLoops} from './candidates';
import {assemble,type Way} from './route';
import {nearestEdge,bounds} from '../src/geo';
import {worldCountries} from './world-countries';
const targets:Record<string,[number,string[]]>={
 baku:[11266687,['Azerbaijan/Baku']],sarthe:[2126739,['France/Le Mans Full']],silverstone:[51160,['United Kingdom/Silverstone GP Wing SF','United Kingdom/Silverstone GP Old SF']],singapore:[421263,['Singapore/Singapore GP']],vegas:[16696508,['United States/Las Vegas GP']],albert:[280443,['Australia/Albert Park']],shanghai:[2094941,['China/Shanghai GP']],suzuka:[284570,['Japan/Suzuka']],cota:[6537729,['United States/Circuit Of The Americas']],mexico:[16251935,['Mexico/Mexico City']],yas:[11378665,['United Arab Emirates/Yas Marina GP']],daytona:[5254136,['United States/Daytona 24 Hour']],watkins:[4872324,['United States/Watkins Glen']],vir:[15765486,['United States/Virginia Int Raceway Full']],redbull:[5309181,['Austria/RedBullRing']]};
const read=async(p:string)=>JSON.parse(await readFile(p,'utf8')),save=async(p:string,x:unknown)=>writeFile(p,JSON.stringify(x,null,2)+'\n');
const args=process.argv.slice(2),archive=args[args.indexOf('--archive')+1];if(!args.includes('--archive')||!archive)throw new Error('Use --archive /absolute/path/to/archive.zip');
const {records}=readTimingArchive(archive),index=await read('data/index.json'),coverage=await read('data/layout-coverage.json'),matches=await read('sources/reference/layout-matches.json');
const code=(c:string)=>({'United Kingdom':'GB','United States':'US'}[c]??worldCountries.find(x=>x.name===c)?.code);
const existingTrackFiles=await Promise.all(index.tracks.map(async(e:any)=>({id:e.id,track:await read(`data/${e.file}`)})));
for(const [label,[relationId,names]] of Object.entries(targets)){
 const expected=records.filter(r=>names.includes(r.id));if(!expected.length){console.log(label,'record names not found');continue;}if(expected.every(r=>existingTrackFiles.some(e=>e.track.layouts.some((l:any)=>l.referenceId===r.id&&l.file!==null))))continue;
 const url=`https://api.openstreetmap.org/api/0.6/relation/${relationId}/full.json`;
 const response=await fetch(url,{headers:{'User-Agent':'OpenRacetrackDB independent source research'}});if(!response.ok){console.log(label,'HTTP',response.status);continue;}
 const raw:any=await response.json(),relation=raw.elements.find((e:any)=>e.type==='relation'&&e.id===relationId),nodes=new Map<number,any>(raw.elements.filter((e:any)=>e.type==='node').map((n:any)=>[n.id,n]));
 const memberRoles=new Map(relation.members.filter((m:any)=>m.type==='way'&&!/pit|alternate|link/.test(m.role)).map((m:any)=>[m.ref,m.role]));
 const ways:Way[]=raw.elements.filter((e:any)=>e.type==='way'&&memberRoles.has(e.id)&&e.tags?.area!=='yes').map((w:any)=>({type:'way',id:w.id,version:w.version,nodes:w.nodes,tags:{...w.tags,oneway:memberRoles.get(w.id)==='backward'?'-1':memberRoles.get(w.id)==='forward'?'yes':w.tags?.highway==='raceway'?w.tags?.oneway:undefined},geometry:w.nodes.map((n:any)=>({lon:nodes.get(n).lon,lat:nodes.get(n).lat}))}));
 const r=expected[0],loops=candidateLoops(ways,400,300);if(r.nominalLengthM)loops.loops.sort((a,b)=>Math.abs(a.lengthM-r.nominalLengthM!)-Math.abs(b.lengthM-r.nominalLengthM!));const distinguishable=loops.loops.length===1||r.nominalLengthM&&loops.loops.length>1&&Math.abs(loops.loops[0].lengthM-r.nominalLengthM)<=Math.max(25,r.nominalLengthM*.0075)&&Math.abs(loops.loops[1].lengthM-r.nominalLengthM)-Math.abs(loops.loops[0].lengthM-r.nominalLengthM)>Math.max(10,r.nominalLengthM*.0025);if(loops.truncated||!distinguishable){console.log(label,'ambiguous',loops.loops.length,loops.truncated);continue;}
 const loop=loops.loops[0],trace=assemble(ways,loop.segments,true);if(nearestEdge(r.gates[0].point,trace).displacementM>100){console.log(label,'timing mismatch');continue;}
 const association=coverage.records.find((e:any)=>e.id===r.id),entry=index.tracks.find((e:any)=>e.id===association?.trackId);
 const country=worldCountries.find(c=>c.code===code(r.country))!,id=entry?.id??`${country.code.toLowerCase()}-${label}-circuit`,folder=entry?`data/${entry.file.replace(/track.json$/,'')}`:`data/${country.slug}/${label}-circuit/`;
 await mkdir(`${folder}layouts`,{recursive:true});await mkdir(`sources/${id}/layouts`,{recursive:true});
 const track=entry?await read(`data/${entry.file}`):{schemaVersion:1,id,name:r.name,aliases:[],country,location:[(bounds(trace)[0]+bounds(trace)[2])/2,(bounds(trace)[1]+bounds(trace)[3])/2],sourceIds:[],defaultLayoutId:'main',layouts:[],sources:[]};
 const file=`relation-${relationId}.json`,sourceId=`osm-relation-${relationId}`,retrievedAt=new Date().toISOString();
 const snapshot=JSON.stringify({attribution:'© OpenStreetMap contributors',retrievedAt,elements:ways,relation:{id:relationId,version:relation.version,tags:relation.tags,members:relation.members}},null,2)+'\n',hash=createHash('sha256').update(snapshot).digest('hex');await writeFile(`sources/${id}/${file}`,snapshot);
 let manifest:any;if(entry&&entry.traceCount>0)manifest=await read(`sources/${id}/import.json`);else{track.location=[(bounds(trace)[0]+bounds(trace)[2])/2,(bounds(trace)[1]+bounds(trace)[3])/2];await writeFile(`sources/${id}/osm.json`,snapshot);manifest={schemaVersion:1,trackId:id,sourceId,snapshotSha256:hash,fetchedAt:retrievedAt,endpoint:url,bbox:bounds(trace)};await writeFile(`sources/${id}/review.md`,`# ${r.name}\n\nSource: ${url}. Named circuit relation ${relationId}, version ${relation.version}. Exact shared-node joins; all route geometry is independent OSM data. Draft identity and travel convention require review.\n`);}
 manifest.snapshots=(manifest.snapshots??[]).filter((s:any)=>s.file!==file);manifest.snapshots.push({file,sha256:hash,sourceId,url,retrievedAt});await save(`sources/${id}/import.json`,manifest);
 if(!track.sources.some((s:any)=>s.id===sourceId))track.sources.push({id:sourceId,type:'osm',title:'OpenStreetMap named circuit relation',url:`https://www.openstreetmap.org/relation/${relationId}`,license:'ODbL-1.0',retrievedAt,evidenceNote:'Circuit identity and exact source-node geometry from a pinned named route relation, including any public-road sections.'});if(!track.sourceIds.includes(sourceId))track.sourceIds.push(sourceId);
 for(const record of expected){const old=coverage.records.find((e:any)=>e.id===record.id);if(old?.layoutIds.length)continue;const current=track.layouts.find((l:any)=>l.referenceId===record.id);if(current?.file)continue;const pending=current;const layoutId=pending?.id??(track.layouts.length?record.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''):'main');
  const note='Draft course from an independently named OSM circuit relation. Timing variants retain separate catalogue entries; private start/finish GPS is displayed locally.';
  await save(`sources/${id}/layouts/${layoutId}.json`,{schemaVersion:1,trackId:id,layoutId,sourceId,snapshotFile:file,snapshotSha256:hash,closed:true,timingMode:'shared',geometryStatus:'draft',reviewedAt:null,notes:[note],segments:loop.segments,gates:[]});if(pending){pending.file=`layouts/${layoutId}.geojson`;pending.description=note;delete pending.missingGeometryReason;}else track.layouts.push({id:layoutId,name:record.name,file:`layouts/${layoutId}.geojson`,description:note});matches[`${id}/${layoutId}`]={recordId:record.id,name:record.name,evidence:`Named OSM circuit relation ${relationId}, version ${relation.version}, independent exact-node source cycle.`};console.log(label,record.name,loop.lengthM);}
 await save(`${folder}track.json`,track);
}
await save('sources/reference/layout-matches.json',matches);
