import {readFile,writeFile,mkdir,stat} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {readTimingArchive} from './reference-timing';
import {simpleCourseChain} from './simple-course-chain';
import {assemble,type Way} from './route';
import {bounds,distance,length,nearestEdge} from '../src/geo';
const args=process.argv.slice(2),archive=args[args.indexOf('--archive')+1];if(!args.includes('--archive')||!archive)throw new Error('Use --archive /absolute/path/to/archive.zip');
const targets=[
 {recordId:'United States/Pikes Peak Hillclimb',relationId:21180239,url:'https://ppihc.org/about/',note:'The event operator identifies the open Pikes Peak Highway climb from the mile-seven start to the summit. The planar source distance differs from the published event distance and supplied distance; the private timing positions agree with the source endpoints.'},
 {recordId:'Germany/Osnabruck Hill Climb',relationId:16137199,url:'https://osnabruecker-bergrennen.de/en/',note:'The event operator identifies the 2.030 km Uphöfener Berg hillclimb. The independently mapped open route measures approximately 2.023 km and both private timing positions agree with its endpoints. The supplied scalar course distance differs and is not used to stretch the geometry.'}
];
const read=async(p:string)=>JSON.parse(await readFile(p,'utf8')),save=async(p:string,x:unknown)=>writeFile(p,JSON.stringify(x,null,2)+'\n');
const {records}=readTimingArchive(archive),registry=await read('sources/reference/catalogue.json'),index=await read('data/index.json'),matches=await read('sources/reference/layout-matches.json');await mkdir('.local/relations',{recursive:true});let added=0;
for(const target of targets){
 const registration=registry.records.find((r:any)=>r.referenceId===target.recordId);if(!registration||registration.geometryAvailable)continue;
 const record=records.find(r=>r.id===target.recordId)!;if(record.gates.length!==2)throw new Error('Open course requires separate timing positions');
 const cache=`.local/relations/${target.relationId}.json`;let raw:any;
 try{raw=await read(cache);}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;const response=await fetch(`https://api.openstreetmap.org/api/0.6/relation/${target.relationId}/full.json`,{headers:{'User-Agent':'OpenRacetrackDB independent road-course research'},signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`Road source HTTP ${response.status}`);raw=await response.json();await save(cache,raw);}
 const relation=raw.elements.find((e:any)=>e.type==='relation'&&e.id===target.relationId);if(!relation)throw new Error('Named road relation missing');
 const members=new Set(relation.members.filter((m:any)=>m.type==='way'&&!/pit|alternat|link/.test(m.role)).map((m:any)=>m.ref)),nodes=new Map<number,any>(raw.elements.filter((e:any)=>e.type==='node').map((e:any)=>[e.id,e]));
 const ways:Way[]=raw.elements.filter((e:any)=>e.type==='way'&&members.has(e.id)).map((w:any)=>({type:'way',id:w.id,version:w.version,tags:w.tags,nodes:w.nodes,geometry:w.nodes.map((n:number)=>{const node=nodes.get(n);if(!node)throw new Error('Missing road source node');return {lon:node.lon,lat:node.lat};})}));
 let segments=simpleCourseChain(ways);if(!segments)throw new Error(`${target.recordId}: road network is not a unique open chain`);
 let trace=assemble(ways,segments,false);if(distance(record.gates[0].point,trace.at(-1)!)<distance(record.gates[0].point,trace[0])){segments=segments.reverse().map(s=>({...s,fromIndex:s.toIndex,toIndex:s.fromIndex}));trace=assemble(ways,segments,false);}
 if(record.gates.some(g=>nearestEdge(g.point,trace).displacementM>30)||distance(record.gates[0].point,trace[0])>30||distance(record.gates[1].point,trace.at(-1)!)>30)throw new Error(`${target.recordId}: endpoints do not agree with timing positions`);
 const entry=index.tracks.find((e:any)=>e.id===registration.trackId),path=`data/${entry.file}`,track=await read(path),layout=track.layouts.find((l:any)=>l.id===registration.layoutId),root=`sources/${track.id}`,file=`named-road-${target.relationId}.json`,sourceId=`osm-road-${target.relationId}`,fetchedAt=(await stat(cache)).mtime.toISOString();
 const bytes=JSON.stringify({attribution:'© OpenStreetMap contributors',retrievedAt:fetchedAt,elements:ways,relation:{id:relation.id,version:relation.version,tags:relation.tags,members:relation.members}},null,2)+'\n',hash=createHash('sha256').update(bytes).digest('hex');await mkdir(`${root}/layouts`,{recursive:true});await writeFile(`${root}/${file}`,bytes);
 let manifest:any;try{manifest=await read(`${root}/import.json`);}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;await writeFile(`${root}/osm.json`,bytes);manifest={schemaVersion:1,trackId:track.id,sourceId,snapshotSha256:hash,fetchedAt,endpoint:`https://api.openstreetmap.org/api/0.6/relation/${target.relationId}/full.json`,bbox:bounds(trace)};await writeFile(`${root}/review.md`,`# ${track.name}\n\nOpen draft course follows a complete independent named road relation. Every join uses exact source node identities. Timing coordinates remain private; historical distances and race-day direction still require review.\n`);}
 manifest.snapshots=(manifest.snapshots??[]).filter((s:any)=>s.file!==file);manifest.snapshots.push({file,sha256:hash,sourceId,url:`https://www.openstreetmap.org/relation/${target.relationId}`,retrievedAt:fetchedAt});await save(`${root}/import.json`,manifest);
 const note=`Draft open course: ${target.note} Coordinates are unchanged independent OSM ways; no artificial closure or endpoint interpolation is added.`;
 for(const source of [{id:sourceId,type:'osm',title:`OpenStreetMap named road course: ${relation.tags.name}`,url:`https://www.openstreetmap.org/relation/${target.relationId}`,license:'ODbL-1.0',retrievedAt:fetchedAt,evidenceNote:'Exact, unbranched road-source chain. Source one-way tags remain unchanged; race-day travel direction is provisional.'},{id:`road-identity-${target.relationId}`,type:'reference',title:'Independent event operator course identification',url:target.url,license:'reference-only',retrievedAt:fetchedAt,evidenceNote:target.note+' Supports identification only; no coordinates are copied.'}])if(!track.sources.some((s:any)=>s.id===source.id))track.sources.push(source);
 if(!track.sourceIds.includes(sourceId))track.sourceIds.push(sourceId);const b=bounds(trace);if(!track.location)track.location=[(b[0]+b[2])/2,(b[1]+b[3])/2];
 await save(`${root}/layouts/${layout.id}.json`,{schemaVersion:1,trackId:track.id,layoutId:layout.id,sourceId,snapshotFile:file,snapshotSha256:hash,closed:false,timingMode:'separate',geometryStatus:'draft',reviewedAt:null,notes:[note],segments,gates:[]});layout.file=`layouts/${layout.id}.geojson`;layout.description=note;delete layout.missingGeometryReason;registration.geometryAvailable=true;matches[`${track.id}/${layout.id}`]={recordId:record.id,name:record.name,evidence:note};await save(path,track);console.log(record.name,length(trace));added++;
}
await save('sources/reference/catalogue.json',registry);await save('sources/reference/layout-matches.json',matches);console.log({added});
