import {readFile,writeFile,mkdir,stat} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {readTimingArchive} from './reference-timing';
import {assemble,type Way} from './route';
import {bounds,nearestEdge} from '../src/geo';
const args=process.argv.slice(2),archive=args[args.indexOf('--archive')+1];if(!args.includes('--archive')||!archive)throw new Error('Use --archive /absolute/path/to/archive.zip');
const {records}=readTimingArchive(archive),read=async(p:string)=>JSON.parse(await readFile(p,'utf8')),save=async(p:string,x:unknown)=>writeFile(p,JSON.stringify(x,null,2)+'\n');
const registry=await read('sources/reference/catalogue.json'),index=await read('data/index.json'),matches=await read('sources/reference/layout-matches.json'),research=await read('.local/relation-course-research.json'),identifications=(await read('sources/reference/course-identifications.json')).records;
const rawCache=new Map<number,{raw:any;ways:Way[]}>();
async function source(id:number){if(rawCache.has(id))return rawCache.get(id)!;const raw=await read(`.local/relations/${id}.json`),nodes=new Map<number,any>(raw.elements.filter((e:any)=>e.type==='node').map((n:any)=>[n.id,n]));const ways:Way[]=raw.elements.filter((e:any)=>e.type==='way').map((w:any)=>({type:'way',id:w.id,version:w.version,nodes:w.nodes,tags:w.tags,geometry:w.nodes.map((n:number)=>({lon:nodes.get(n).lon,lat:nodes.get(n).lat}))}));const result={raw,ways};rawCache.set(id,result);return result;}
let added=0;
for(const record of records){const registration=registry.records.find((r:any)=>r.referenceId===record.id);if(registration.geometryAvailable||!record.nominalLengthM)continue;const candidates:any[]=[],keys=new Set<string>(),identification=identifications.find((i:any)=>i.referenceId===record.id);
 for(const researchRow of research.filter((r:any)=>r.recordId===record.id&&r.complete&&(!identification||r.relationId===identification.relationId)))for(const candidate of researchRow.candidates){if(identification&&(researchRow.relationName!==identification.relationName||researchRow.candidates.length!==1))throw new Error('Explicit course identity changed or became ambiguous');const {raw,ways}=await source(researchRow.relationId),trace=assemble(ways,candidate.segments,true);const names=candidate.segments.map((s:any)=>ways.find(w=>w.id===s.wayId)?.tags?.name??'').join(' ');if(/1c[- ]?v2/i.test(record.name)&&!/chicane nord/i.test(names))continue;
  const key=trace.slice(1).map((p,i)=>[trace[i].join(','),p.join(',')].sort().join(':')).sort().join('|');if(keys.has(key))continue;keys.add(key);if(nearestEdge(record.gates[0].point,trace).displacementM>30)continue;candidates.push({candidate,raw,ways,trace,relationId:researchRow.relationId,relationName:researchRow.relationName});
 }
 candidates.sort((a,b)=>a.candidate.delta-b.candidate.delta);if(!candidates.length||candidates[0].candidate.delta>(identification?.maximumDistanceDifferenceM??Math.max(25,record.nominalLengthM*.0075))||candidates.length>1&&candidates[1].candidate.delta-candidates[0].candidate.delta<Math.max(10,record.nominalLengthM*.0025))continue;
 const selected=candidates[0],entry=index.tracks.find((e:any)=>e.id===registration.trackId),path=`data/${entry.file}`,track=await read(path),layout=track.layouts.find((l:any)=>l.referenceId===record.id);if(layout.file!==null)continue;
 const dir=`sources/${track.id}`,file=`named-circuit-${selected.relationId}.json`,sourceId=`osm-circuit-${selected.relationId}`,relation=selected.raw.elements.find((e:any)=>e.type==='relation'&&e.id===selected.relationId),fetchedAt=(await stat(`.local/relations/${selected.relationId}.json`)).mtime.toISOString(),bytes=JSON.stringify({attribution:'© OpenStreetMap contributors',retrievedAt:fetchedAt,elements:selected.ways,relation:{id:relation.id,version:relation.version,tags:relation.tags,members:relation.members}},null,2)+'\n',hash=createHash('sha256').update(bytes).digest('hex');await mkdir(`${dir}/layouts`,{recursive:true});
 let manifest:any;try{manifest=await read(`${dir}/import.json`);}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;await writeFile(`${dir}/osm.json`,bytes);manifest={schemaVersion:1,trackId:track.id,sourceId,snapshotSha256:hash,fetchedAt,endpoint:`https://api.openstreetmap.org/api/0.6/relation/${selected.relationId}/full.json`,bbox:bounds(selected.trace)};await writeFile(`${dir}/review.md`,`# ${track.name}\n\nDraft course identification using a named OSM circuit relation. Route coordinates and joins are exact independent source data. Layout identity and travel direction require visual review.\n`);}
 // Reuse a pinned relation snapshot when several timing records share its course.
 let snapshotHash=hash;try{const existing=await readFile(`${dir}/${file}`,'utf8');snapshotHash=createHash('sha256').update(existing).digest('hex');assemble(JSON.parse(existing).elements,selected.candidate.segments,true);}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;await writeFile(`${dir}/${file}`,bytes);}
 manifest.snapshots=(manifest.snapshots??[]).filter((s:any)=>s.file!==file);manifest.snapshots.push({file,sha256:snapshotHash,sourceId,url:`https://www.openstreetmap.org/relation/${selected.relationId}`,retrievedAt:fetchedAt});await save(`${dir}/import.json`,manifest);
 if(!track.location){const b=bounds(selected.trace);track.location=[(b[0]+b[2])/2,(b[1]+b[3])/2];}if(!track.sourceIds.includes(sourceId))track.sourceIds.push(sourceId);if(!track.sources.some((s:any)=>s.id===sourceId))track.sources.push({id:sourceId,type:'osm',title:`OpenStreetMap circuit relation: ${selected.relationName??selected.relationId}`,url:`https://www.openstreetmap.org/relation/${selected.relationId}`,license:'ODbL-1.0',retrievedAt:fetchedAt,evidenceNote:'Pinned independent circuit ways include public-road sections. Source-node connectivity is exact. Course association uses timing location and declared length; travel direction remains provisional.'});
 if(identification&&!track.sources.some((s:any)=>s.id===`course-identity-${selected.relationId}`))track.sources.push({id:`course-identity-${selected.relationId}`,type:'reference',title:'Independent operator or event course identification',url:identification.url,license:'reference-only',retrievedAt:fetchedAt,evidenceNote:identification.evidence+' Identification only; no coordinates are copied.'});
 const note=`${identification?identification.evidence+' ':''}Draft configuration selected from the independently named circuit relation ${selected.relationId}. The source route passes timing and course-distance checks. Layout identity and travel direction still require visual review.`;
 await save(`${dir}/layouts/${layout.id}.json`,{schemaVersion:1,trackId:track.id,layoutId:layout.id,sourceId,snapshotFile:file,snapshotSha256:snapshotHash,closed:true,timingMode:'shared',geometryStatus:'draft',reviewedAt:null,notes:[note,'Source one-way tags are preserved. Relation routes can follow a race-day direction different from ordinary road use; travel direction is provisional.'],segments:selected.candidate.segments,gates:[]});layout.file=`layouts/${layout.id}.geojson`;layout.description=note;delete layout.missingGeometryReason;await save(path,track);registration.geometryAvailable=true;matches[`${track.id}/${layout.id}`]={recordId:record.id,name:record.name,evidence:note};console.log(record.name,selected.candidate.lengthM,selected.relationId);added++;
}
await save('sources/reference/catalogue.json',registry);await save('sources/reference/layout-matches.json',matches);console.log({added});
