import {createHash} from 'node:crypto';
import {readFile,writeFile,mkdir} from 'node:fs/promises';import {candidateLoops} from './candidates';import {anchoredCourses} from './anchored-courses';import {readTimingArchive} from './reference-timing';import {nearestEdge,length} from '../src/geo';import {assemble,type Way} from './route';
const args=process.argv.slice(2),archive=args[args.indexOf('--archive')+1];if(!args.includes('--archive')||!archive)throw new Error('Use --archive /absolute/path/to/archive.zip');
const {records}=readTimingArchive(archive),read=async(p:string)=>JSON.parse(await readFile(p,'utf8')),registry=await read('sources/reference/catalogue.json'),relationBytes=await readFile('sources/course-relations/osm.json','utf8'),relationManifest=await read('sources/course-relations/import.json'),relations=JSON.parse(relationBytes).elements;if(createHash('sha256').update(relationBytes).digest('hex')!==relationManifest.snapshotSha256)throw new Error('Circuit relation snapshot hash mismatch');await mkdir('.local/relations',{recursive:true});const report:any[]=[];
for(const relation of relations){const paths=relation.members.filter((m:any)=>m.type==='way'&&m.geometry?.length>1).map((m:any)=>m.geometry.map((p:any)=>[p.lon,p.lat]));const expected=records.filter(r=>!registry.records.find((x:any)=>x.referenceId===r.id).geometryAvailable&&r.nominalLengthM&&r.gates.length===1&&paths.some((p:any)=>nearestEdge(r.gates[0].point,p).displacementM<30));if(!expected.length)continue;
 let raw:any;try{raw=await read(`.local/relations/${relation.id}.json`);}catch{const res=await fetch(`https://api.openstreetmap.org/api/0.6/relation/${relation.id}/full.json`,{headers:{'User-Agent':'OpenRacetrackDB circuit research'},signal:AbortSignal.timeout(20000)});if(!res.ok){console.log(relation.id,'HTTP',res.status);continue;}raw=await res.json();await writeFile(`.local/relations/${relation.id}.json`,JSON.stringify(raw));}
 const members=raw.elements.find((e:any)=>e.type==='relation'&&e.id===relation.id).members,nodes=new Map<number,any>(raw.elements.filter((e:any)=>e.type==='node').map((n:any)=>[n.id,n])),selected=new Set(members.filter((m:any)=>m.type==='way'&&!/pit|alternat|link/.test(m.role)).map((m:any)=>m.ref));const ways:Way[]=raw.elements.filter((w:any)=>w.type==='way'&&selected.has(w.id)&&w.tags?.area!=='yes'&&!/^pit[_ -]?lane$/i.test(w.tags?.service??'')&&!/^pit[_ -]?lane$/i.test(w.tags?.raceway??'')&&!/pit[ _-]?(lane|road|entry|exit)|boxengasse|boxenausfahrt|^stand$/i.test(w.tags?.name??'')).map((w:any)=>({...w,tags:{...w.tags,oneway:undefined},geometry:w.nodes.map((n:number)=>({lon:nodes.get(n).lon,lat:nodes.get(n).lat}))}));
 const loops=candidateLoops(ways,3000,40);console.log(relation.id,relation.tags.name,'cycles',loops.loops.length,'truncated',loops.truncated);
 for(const record of expected){const focused=loops.truncated?anchoredCourses(ways,record.gates[0].point,record.nominalLengthM!,{maximumSteps:500000}):undefined;const candidates=focused?focused.candidates:loops.loops.map(l=>({...l,displacementM:nearestEdge(record.gates[0].point,assemble(ways,l.segments,true)).displacementM}));const c=candidates.filter(l=>l.displacementM<=30).sort((a,b)=>Math.abs(a.lengthM-record.nominalLengthM!)-Math.abs(b.lengthM-record.nominalLengthM!));report.push({recordId:record.id,relationId:relation.id,relationName:relation.tags.name,complete:focused?!focused.truncated:!loops.truncated,candidates:c.slice(0,4).map(l=>({lengthM:l.lengthM,delta:Math.abs(l.lengthM-record.nominalLengthM!),displacementM:l.displacementM,segments:l.segments})),totalLength:ways.reduce((s,w)=>s+length(w.geometry.map(p=>[p.lon,p.lat])),0)});}
}
await writeFile('.local/relation-course-research.json',JSON.stringify(report,null,2)+'\n');
