import {z} from 'zod';
import {bounds,distance,equal,intersects,length,networkLength,type Position} from '../src/geo';
const slug=z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),text=z.string().min(1);
export const position=z.tuple([z.number().min(-180).max(180),z.number().min(-90).max(90)]);
const path=z.string().refine(s=>!s.includes('..')&&!s.includes('\\')&&!s.startsWith('/')&&!s.includes(':')&&s.length>0,'Unsafe relative path');
const country=z.strictObject({code:z.string().regex(/^[A-Z]{2}$/),name:text,slug});
const source=z.strictObject({id:slug,type:z.enum(['osm','survey','permission','reference']),title:text,url:z.url().refine(s=>/^https?:/.test(s)),license:text,retrievedAt:z.iso.datetime(),evidenceNote:text});
const entry=z.strictObject({id:slug,name:text,file:path.nullable(),referenceId:text.optional(),missingGeometryReason:text.optional(),description:z.string().optional()});
export const trackSchema=z.strictObject({schemaVersion:z.literal(1),id:slug,name:text,aliases:z.array(text),country,locality:text.optional(),location:position.nullable(),sourceIds:z.array(slug),defaultLayoutId:slug,layouts:z.array(entry).min(1),sources:z.array(source)});
export const indexSchema=z.strictObject({schemaVersion:z.literal(1),tracks:z.array(z.strictObject({id:slug,name:text,aliases:z.array(text),country,locality:text.optional(),location:position.nullable(),file:path,traceCount:z.number().int().nonnegative(),layoutCount:z.number().int().positive()}))});
const traceProps=z.strictObject({role:z.literal('trace'),sourceIds:z.array(slug).min(1)});
const gateProps=z.strictObject({role:z.enum(['start_finish','start','finish']),sourceIds:z.array(slug).min(1),positionStatus:z.enum(['verified','estimated']),endpointMethod:z.enum(['source-endpoints','perpendicular-display']),positionNote:text});
const line=z.strictObject({type:z.literal('LineString'),coordinates:z.array(position).min(2)});
const network=z.strictObject({type:z.literal('MultiLineString'),coordinates:z.array(z.array(position).min(2)).min(2)});
export const layoutSchema=z.strictObject({type:z.literal('FeatureCollection'),bbox:z.tuple([z.number(),z.number(),z.number(),z.number()]),metadata:z.strictObject({schemaVersion:z.union([z.literal(1),z.literal(2)]),geometryKind:z.literal('network').optional(),trackId:slug,layoutId:slug,license:z.literal('ODbL-1.0'),attribution:text,closed:z.boolean(),geometryStatus:z.enum(['draft','reviewed']),timingStatus:z.enum(['missing','partial','estimated','verified']),timingMode:z.enum(['shared','separate']),lengthM:z.number().positive(),reviewedAt:z.iso.date().nullable(),notes:z.array(z.string())}),features:z.array(z.strictObject({type:z.literal('Feature'),id:slug,properties:z.union([traceProps,gateProps]),geometry:z.union([line,network])})).min(1)});
export type Track=z.infer<typeof trackSchema>;export type Catalogue=z.infer<typeof indexSchema>;export type Layout=z.infer<typeof layoutSchema>;
export function geometryPaths(geometry:Layout['features'][number]['geometry']):Position[][]{return geometry.type==='LineString'?[geometry.coordinates]:geometry.coordinates;}
export function validateTrack(input:unknown){const track=trackSchema.parse(input);unique(track.layouts.map(l=>l.id),'layout IDs');unique(track.sources.map(s=>s.id),'source IDs');if(!track.layouts.some(l=>l.id===track.defaultLayoutId))throw new Error('defaultLayoutId: unknown layout');checkSources(track.sourceIds,track,false);for(const l of track.layouts){if(l.file!==null&&l.file!==`layouts/${l.id}.geojson`)throw new Error(`${l.id}: layout path must match ID`);if(l.file===null&&!l.missingGeometryReason)throw new Error(`${l.id}: missing trace requires a reason`);}
 if(track.layouts.some(l=>l.file!==null)&&(!track.location||!track.sourceIds.length||!track.sources.length))throw new Error('Traced venue requires independent location and sources');
 unique(track.layouts.flatMap(l=>l.referenceId?[l.referenceId]:[]),'reference layout IDs');return track;}
function unique(ids:string[],field:string){if(new Set(ids).size!==ids.length)throw new Error(`${field}: duplicate IDs`);}
function checkSources(ids:string[],track:Track,coordinates=true){for(const id of ids){const source=track.sources.find(s=>s.id===id);if(!source)throw new Error(`sourceIds: unknown ${id}`);if(coordinates&&(source.type==='reference'||source.license==='reference-only'))throw new Error(`sourceIds: ${id} is reference-only`);}}
export function validateLayout(input:unknown,track:Track,id:string){const data=layoutSchema.parse(input),m=data.metadata; if(m.trackId!==track.id||m.layoutId!==id)throw new Error('metadata: track/layout identity mismatch');unique(data.features.map(f=>f.id),'feature IDs');const traces=data.features.filter(f=>f.properties.role==='trace');if(traces.length!==1||traces[0].id!=='trace')throw new Error('features: expected one trace');const paths=geometryPaths(traces[0].geometry),trace=paths[0],isNetwork=m.geometryKind==='network';if(isNetwork){if(m.schemaVersion!==2||m.closed||traces[0].geometry.type!=='MultiLineString')throw new Error('network: requires schema 2, multiple paths and no single-route closure');}else if(m.schemaVersion!==1||traces[0].geometry.type!=='LineString')throw new Error('route: requires schema 1 and one LineString');for(const f of data.features){checkSources(f.properties.sourceIds,track);for(const path of geometryPaths(f.geometry))for(let i=1;i<path.length;i++)if(equal(path[i],path[i-1]))throw new Error(`${f.id}: adjacent duplicate coordinates`);if(f.id!==f.properties.role)throw new Error(`${f.id}: ID must match role`);}
 if(!isNetwork&&m.closed!==equal(trace[0],trace.at(-1)!))throw new Error('trace: closure disagrees with closed flag');if(m.closed&&new Set(trace.map(p=>p.join(','))).size<3)throw new Error('trace: insufficient distinct points');if(Math.abs((isNetwork?networkLength(paths):length(trace))-m.lengthM)>.2)throw new Error('metadata.lengthM: incorrect length');const bbox=bounds(data.features.flatMap(f=>geometryPaths(f.geometry).flat()));if(bbox.some((v,i)=>Math.abs(v-data.bbox[i])>1e-8))throw new Error('bbox: incorrect bounds');if(bbox[2]-bbox[0]>180)throw new Error('bbox: antimeridian unsupported');if(m.geometryStatus==='reviewed'&&!m.reviewedAt)throw new Error('metadata.reviewedAt: required for reviewed geometry');
 const gates=data.features.filter(f=>f.properties.role!=='trace');if(m.timingMode==='shared'&&gates.some(f=>f.id!=='start_finish')||m.timingMode==='separate'&&gates.some(f=>f.id==='start_finish'))throw new Error('features: incompatible gate roles');const status=!gates.length?'missing':m.timingMode==='separate'&&gates.length===1?'partial':gates.every(f=>'positionStatus' in f.properties&&f.properties.positionStatus==='verified')?'verified':'estimated';if(status!==m.timingStatus)throw new Error('metadata.timingStatus: contradicts features');
 for(const gate of gates){if(gate.geometry.type!=='LineString')throw new Error('gate: requires one LineString');const g=gate.geometry.coordinates;if(g.length!==2)throw new Error(`${gate.id}: expected two endpoints`);if(!paths.some(path=>path.slice(1).some((p,i)=>intersects(path[i],p,g[0],g[1]))))throw new Error(`${gate.id}: gate does not intersect trace`);if(!isNetwork&&!m.closed&&status==='verified'){const endpoint=gate.id==='start'?trace[0]:trace.at(-1)!;if(!intersects(endpoint,[endpoint[0]+1e-9,endpoint[1]+1e-9],g[0],g[1])&&distance(endpoint,[(g[0][0]+g[1][0])/2,(g[0][1]+g[1][1])/2])>.5)throw new Error(`${gate.id}: open trace endpoint must coincide with gate`);}}
 return data;
}
