import {z} from 'zod';
import {bounds,distance,equal,intersects,length} from '../src/geo';
const slug=z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),text=z.string().min(1);
export const position=z.tuple([z.number().min(-180).max(180),z.number().min(-90).max(90)]);
const path=z.string().refine(s=>!s.includes('..')&&!s.includes('\\')&&!s.startsWith('/')&&!s.includes(':')&&s.length>0,'Unsafe relative path');
const country=z.strictObject({code:z.string().regex(/^[A-Z]{2}$/),name:text,slug});
const source=z.strictObject({id:slug,type:z.enum(['osm','survey','permission','reference']),title:text,url:z.url().refine(s=>/^https?:/.test(s)),license:text,retrievedAt:z.iso.datetime(),evidenceNote:text});
const entry=z.strictObject({id:slug,name:text,file:path,description:z.string().optional()});
export const trackSchema=z.strictObject({schemaVersion:z.literal(1),id:slug,name:text,aliases:z.array(text),country,locality:text.optional(),location:position,sourceIds:z.array(slug).min(1),defaultLayoutId:slug,layouts:z.array(entry).min(1),sources:z.array(source).min(1)});
export const indexSchema=z.strictObject({schemaVersion:z.literal(1),tracks:z.array(z.strictObject({id:slug,name:text,aliases:z.array(text),country,locality:text.optional(),location:position,file:path,layoutCount:z.number().int().positive()}))});
const traceProps=z.strictObject({role:z.literal('trace'),sourceIds:z.array(slug).min(1)});
const gateProps=z.strictObject({role:z.enum(['start_finish','start','finish']),sourceIds:z.array(slug).min(1),positionStatus:z.enum(['verified','estimated']),endpointMethod:z.enum(['source-endpoints','perpendicular-display']),positionNote:text});
export const layoutSchema=z.strictObject({type:z.literal('FeatureCollection'),bbox:z.tuple([z.number(),z.number(),z.number(),z.number()]),metadata:z.strictObject({schemaVersion:z.literal(1),trackId:slug,layoutId:slug,license:z.literal('ODbL-1.0'),attribution:text,closed:z.boolean(),geometryStatus:z.enum(['draft','reviewed']),timingStatus:z.enum(['missing','partial','estimated','verified']),timingMode:z.enum(['shared','separate']),lengthM:z.number().positive(),reviewedAt:z.iso.date().nullable(),notes:z.array(z.string())}),features:z.array(z.strictObject({type:z.literal('Feature'),id:slug,properties:z.union([traceProps,gateProps]),geometry:z.strictObject({type:z.literal('LineString'),coordinates:z.array(position).min(2)})})).min(1)});
export type Track=z.infer<typeof trackSchema>;export type Catalogue=z.infer<typeof indexSchema>;export type Layout=z.infer<typeof layoutSchema>;
export function validateTrack(input:unknown){const track=trackSchema.parse(input);unique(track.layouts.map(l=>l.id),'layout IDs');unique(track.sources.map(s=>s.id),'source IDs');if(!track.layouts.some(l=>l.id===track.defaultLayoutId))throw new Error('defaultLayoutId: unknown layout');checkSources(track.sourceIds,track,false);for(const l of track.layouts)if(l.file!==`layouts/${l.id}.geojson`)throw new Error(`${l.id}: layout path must match ID`);return track;}
function unique(ids:string[],field:string){if(new Set(ids).size!==ids.length)throw new Error(`${field}: duplicate IDs`);}
function checkSources(ids:string[],track:Track,coordinates=true){for(const id of ids){const source=track.sources.find(s=>s.id===id);if(!source)throw new Error(`sourceIds: unknown ${id}`);if(coordinates&&(source.type==='reference'||source.license==='reference-only'))throw new Error(`sourceIds: ${id} is reference-only`);}}
export function validateLayout(input:unknown,track:Track,id:string){const data=layoutSchema.parse(input),m=data.metadata; if(m.trackId!==track.id||m.layoutId!==id)throw new Error('metadata: track/layout identity mismatch');unique(data.features.map(f=>f.id),'feature IDs');const traces=data.features.filter(f=>f.properties.role==='trace');if(traces.length!==1||traces[0].id!=='trace')throw new Error('features: expected one trace');const trace=traces[0].geometry.coordinates;for(const f of data.features){checkSources(f.properties.sourceIds,track);for(let i=1;i<f.geometry.coordinates.length;i++)if(equal(f.geometry.coordinates[i],f.geometry.coordinates[i-1]))throw new Error(`${f.id}: adjacent duplicate coordinates`);if(f.id!==f.properties.role)throw new Error(`${f.id}: ID must match role`);}
 if(m.closed!==equal(trace[0],trace.at(-1)!))throw new Error('trace: closure disagrees with closed flag');if(m.closed&&new Set(trace.map(p=>p.join(','))).size<3)throw new Error('trace: insufficient distinct points');if(Math.abs(length(trace)-m.lengthM)>.2)throw new Error('metadata.lengthM: incorrect length');const bbox=bounds(data.features.flatMap(f=>f.geometry.coordinates));if(bbox.some((v,i)=>Math.abs(v-data.bbox[i])>1e-8))throw new Error('bbox: incorrect bounds');if(bbox[2]-bbox[0]>180)throw new Error('bbox: antimeridian unsupported');if(m.geometryStatus==='reviewed'&&!m.reviewedAt)throw new Error('metadata.reviewedAt: required for reviewed geometry');
 const gates=data.features.filter(f=>f.properties.role!=='trace');if(m.timingMode==='shared'&&gates.some(f=>f.id!=='start_finish')||m.timingMode==='separate'&&gates.some(f=>f.id==='start_finish'))throw new Error('features: incompatible gate roles');const status=!gates.length?'missing':m.timingMode==='separate'&&gates.length===1?'partial':gates.every(f=>'positionStatus' in f.properties&&f.properties.positionStatus==='verified')?'verified':'estimated';if(status!==m.timingStatus)throw new Error('metadata.timingStatus: contradicts features');
 for(const gate of gates){const g=gate.geometry.coordinates;if(g.length!==2)throw new Error(`${gate.id}: expected two endpoints`);if(!trace.slice(1).some((p,i)=>intersects(trace[i],p,g[0],g[1])))throw new Error(`${gate.id}: gate does not intersect trace`);if(!m.closed&&status==='verified'){const endpoint=gate.id==='start'?trace[0]:trace.at(-1)!;if(!intersects(endpoint,[endpoint[0]+1e-9,endpoint[1]+1e-9],g[0],g[1])&&distance(endpoint,[(g[0][0]+g[1][0])/2,(g[0][1]+g[1][1])/2])>.5)throw new Error(`${gate.id}: open trace endpoint must coincide with gate`);}}
 return data;
}
