export type Position=[number,number];
export const R=6371008.8,rad=Math.PI/180;
export const equal=(a:Position,b:Position)=>a[0]===b[0]&&a[1]===b[1];
export function distance(a:Position,b:Position){const h=Math.sin((b[1]-a[1])*rad/2)**2+Math.cos(a[1]*rad)*Math.cos(b[1]*rad)*Math.sin((b[0]-a[0])*rad/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(h)));}
export function length(points:Position[]){return Math.round(points.slice(1).reduce((sum,p,i)=>sum+distance(points[i],p),0)*10)/10;}
export function bounds(points:Position[]):[number,number,number,number]{return [Math.min(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1])),Math.max(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1]))];}
export function plane(origin:Position){const k=R*rad,cos=Math.cos(origin[1]*rad);return {to:(p:Position):Position=>[(p[0]-origin[0])*k*cos,(p[1]-origin[1])*k],from:(p:Position):Position=>[Number((origin[0]+p[0]/k/cos).toFixed(7)),Number((origin[1]+p[1]/k).toFixed(7))]};}
export function project(point:Position,a:Position,b:Position){const local=plane(point),u=local.to(a),v=local.to(b),dx=v[0]-u[0],dy=v[1]-u[1],den=dx*dx+dy*dy;if(!den)throw new Error('Degenerate anchor edge');const t=Math.max(0,Math.min(1,-(u[0]*dx+u[1]*dy)/den));const hit:Position=[u[0]+t*dx,u[1]+t*dy];return {t,point:local.from(hit),displacementM:Math.hypot(...hit),tangent:[dx/Math.sqrt(den),dy/Math.sqrt(den)] as Position};}
export function displayGate(point:Position,a:Position,b:Position,width=25,maxDisplacement=5){const p=project(point,a,b);if(p.displacementM>maxDisplacement)throw new Error(`Timing projection ${p.displacementM.toFixed(2)} m exceeds ${maxDisplacement} m; review anchor`);const local=plane(p.point),[dx,dy]=p.tangent;return {coordinates:[local.from([-dy*width/2,dx*width/2]),local.from([dy*width/2,-dx*width/2])] as Position[],...p};}
export function nearestEdge(point:Position,trace:Position[]){let best={index:0,...project(point,trace[0],trace[1])};for(let i=1;i<trace.length-1;i++){const p=project(point,trace[i],trace[i+1]);if(p.displacementM<best.displacementM)best={index:i,...p};}return best;}
export function intersects(a:Position,b:Position,c:Position,d:Position,tolerance=.5){const local=plane(a),u=local.to(b),v=local.to(c),w=local.to(d),dx=w[0]-v[0],dy=w[1]-v[1],det=u[0]*dy-u[1]*dx;if(Math.abs(det)<1e-10)return false;const t=(v[0]*dy-v[1]*dx)/det,s=(v[0]*u[1]-v[1]*u[0])/det;return t>=-tolerance/Math.hypot(...u)&&t<=1+tolerance/Math.hypot(...u)&&s>=-tolerance/Math.hypot(dx,dy)&&s<=1+tolerance/Math.hypot(dx,dy);}
// Travel forward across the loop boundary when the finish precedes the start in storage order.
export function trimLoop(trace:Position[],start:{index:number;point:Position},finish:{index:number;point:Position}){const ring=equal(trace[0],trace.at(-1)!)?trace.slice(0,-1):trace;const points=[start.point];let i=(start.index+1)%ring.length;for(let count=0;count<ring.length;count++){if(i===(finish.index+1)%ring.length)break;points.push(ring[i]);i=(i+1)%ring.length;}points.push(finish.point);return points.filter((p,i)=>!i||!equal(p,points[i-1]));}
