import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import './style.css';
import {indexSchema,validateTrack,validateLayout,type Catalogue,type Track,type Layout} from '../schemas/data';
import {trimLoop,length,bounds,type Position} from './geo';
import {localGate} from './local-timing';
const base=import.meta.env.BASE_URL;
const config={tiles:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>',maxZoom:19,trace:{color:'#ffb347',weight:5},outline:{color:'#33281b',weight:9}};
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<header><a class="brand" href="${base}"><span class="brand-icon">↳</span><span>Open Racetrack<span class="brand-sub">DATABASE</span></span></a><span class="edition">Worldwide preview <span class="live-dot"></span></span><a class="header-link" href="https://github.com/markthebault/open-racetrack-db">Source repository ↗</a></header><main><aside><div class="intro"><span class="eyebrow">THE CIRCUIT AT A GLANCE</span><h1>Find your next<br><em>starting line.</em></h1><p>Explore racetracks, switch layouts, and see where each lap begins.</p></div><section class="browse"><div class="browse-heading"><h2>Explore tracks</h2><span id="count"></span></div><label for="search">Search tracks</label><input id="search" type="search" placeholder="Name, alias, or locality"><label for="country">Country</label><select id="country"><option value="">All countries</option></select><div id="venues" class="venues"></div><button id="reset" class="text-button">Reset filters</button></section><section id="selection" class="selection"><p class="placeholder">Choose a track to explore its layouts.</p></section><footer>Track traces © OpenStreetMap contributors.<br><a href="https://opendatacommons.org/licenses/odbl/1-0/">Database ODbL 1.0</a> · <a href="https://opensource.org/license/mit">Code MIT</a></footer></aside><section class="map-area" aria-label="Track map"><div id="map"></div><div class="map-title"><span class="eyebrow">TRACK ATLAS</span><strong id="map-name">Explore circuits worldwide.</strong></div><div class="legend"><span><i class="trace-swatch"></i> Track trace</span><span><i class="gate-swatch"></i> Start / finish</span></div><div id="tile-notice" hidden>Background map unavailable. Track traces still work.</div><div id="message" role="status" aria-live="polite"></div></section></main>`;
const get=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const map=L.map('map',{zoomControl:false}).setView([49,7],5);L.control.zoom({position:'bottomright'}).addTo(map);const tiles=L.tileLayer(config.tiles,{attribution:config.attribution,maxZoom:config.maxZoom}).addTo(map);tiles.on('tileerror',()=>{get('tile-notice').hidden=false;});
const markers=L.layerGroup().addTo(map),selectedLayers=L.layerGroup().addTo(map);
let catalogue:Catalogue,track:Track|undefined,layout:Layout|undefined,layoutFile:string|undefined,sequence=0,abort:AbortController|undefined;
const cache=new Map<string,unknown>();
type LocalTiming={name:string;association?:'proximity-only';gates:{role:'start_finish'|'start'|'finish';point:Position}[]};
let localTiming:Record<string,LocalTiming>={};
try{const r=await fetch(`${base}local/timing.json`);if(r.ok&&r.headers.get('content-type')?.includes('json'))localTiming=await r.json();}catch{/* Public hosts have no private overlay. */}
const clean=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function message(text:string){get('message').textContent=text;}
async function load(path:string,signal?:AbortSignal){if(cache.has(path))return cache.get(path);const r=await fetch(`${base}data/${path}`,{signal});if(!r.ok)throw new Error(`Could not load ${path}: HTTP ${r.status}`);const data=await r.json();cache.set(path,data);return data;}
function element<K extends keyof HTMLElementTagNameMap>(tag:K,text:string,className?:string){const e=document.createElement(tag);e.textContent=text;if(className)e.className=className;return e;}
function urlState(trackId?:string,layoutId?:string,replace=false){const url=new URL(location.href);url.searchParams.delete('track');url.searchParams.delete('layout');if(trackId)url.searchParams.set('track',trackId);if(layoutId)url.searchParams.set('layout',layoutId);if(url.href!==location.href)history[replace?'replaceState':'pushState']({},'',url);}
function clear(){document.querySelector('aside')!.classList.remove('has-selection');sequence++;abort?.abort();track=undefined;layout=undefined;layoutFile=undefined;selectedLayers.clearLayers();get('selection').replaceChildren(element('p','Choose a track to explore its layouts.','placeholder'));get('map-name').textContent=`${catalogue.tracks.length} venues. ${catalogue.tracks.reduce((sum,t)=>sum+t.layoutCount,0)} layouts.`;}
function visible(){const query=clean(get<HTMLInputElement>('search').value),country=get<HTMLSelectElement>('country').value;return catalogue.tracks.filter(t=>(!country||t.country.code===country)&&clean([t.name,...t.aliases,t.locality??''].join(' ')).includes(query)).sort((a,b)=>a.country.name.localeCompare(b.country.name)||a.name.localeCompare(b.name));}
function renderCatalogue(filterChanged=false){const found=visible();if(filterChanged&&track&&!found.some(t=>t.id===track!.id)){clear();urlState();}get('count').textContent=`${found.length} tracks`;const list=get('venues');list.replaceChildren();markers.clearLayers();for(const t of found){const button=element('button','','venue');button.dataset.trackId=t.id;button.classList.toggle('active',track?.id===t.id);button.append(element('span',t.name,'venue-name'),element('span',`${t.country.name} · ${t.layoutCount} ${t.layoutCount===1?'layout':'layouts'}`,'venue-meta'));button.addEventListener('click',()=>select(t.id));list.append(button);const marker=L.circleMarker([t.location[1],t.location[0]],{radius:track?.id===t.id?8:6,color:'#253c32',weight:2,fillColor:'#e8ab52',fillOpacity:1});marker.bindTooltip(element('span',t.name));marker.on('click',()=>select(t.id));markers.addLayer(marker);}if(!found.length)list.append(element('p','No tracks match your filters'));}
function fit(){const group=selectedLayers as L.FeatureGroup;const points:L.LatLng[]=[];group.eachLayer(layer=>{if(layer instanceof L.Polyline)points.push(...(layer.getLatLngs() as L.LatLng[]));});if(points.length)map.fitBounds(L.latLngBounds(points),{padding:[65,65],maxZoom:17,animate:false});}
function draw(data:Layout,privateGateLines:{role:string;coordinates:Position[];note:string}[]=[]){selectedLayers.clearLayers();for(const feature of data.features){const coords=feature.geometry.coordinates.map(p=>L.latLng(p[1],p[0]));if(feature.properties.role==='trace'){L.polyline(coords,config.outline).addTo(selectedLayers);L.polyline(coords,config.trace).addTo(selectedLayers);}else{const props=feature.properties;drawGate(props.role,feature.geometry.coordinates,`${props.positionStatus} position; ${props.endpointMethod}`,props.positionStatus==='estimated');}}
 for(const gate of privateGateLines)drawGate(gate.role,gate.coordinates,gate.note,true);fit();}
function drawGate(role:string,coords:Position[],note:string,dashed:boolean){const label=role==='start_finish'?'Start / finish':role==='start'?'Start':'Finish',color=role==='finish'?'#de5b5b':'#19a28a';L.polyline(coords.map(p=>[p[1],p[0]] as L.LatLngTuple),{color,weight:4,dashArray:dashed?'5 4':undefined}).bindTooltip(note).addTo(selectedLayers);const center:L.LatLngTuple=[(coords[0][1]+coords[1][1])/2,(coords[0][0]+coords[1][0])/2];L.circleMarker(center,{radius:5,color,fillOpacity:1}).bindTooltip(`${label} · ${dashed?'Estimated position':'Verified position'}`,{permanent:true,direction:'right',className:'gate-label'}).addTo(selectedLayers);}
function sourceLinks(panel:HTMLElement,selected:Track){const details=element('details',''),summary=element('summary','Sources & data');details.append(summary);for(const source of selected.sources){const a=element('a',source.title);a.href=source.url;a.target='_blank';a.rel='noreferrer';details.append(a,element('p',`${source.license} · Retrieved ${source.retrievedAt.slice(0,10)}`),element('p',source.evidenceNote));}details.append(element('p','Track traces © OpenStreetMap contributors. ODbL 1.0. Approximate geographic traces, not surveyed centerlines.'));panel.append(details);}
function panel(selected:Track,requested:string,state:'loading'|'ready'|'error',error?:string,privateNotes:string[]=[]){const root=get('selection');root.replaceChildren();root.append(element('span','SELECTED VENUE','eyebrow'),element('h2',selected.name),element('p',[selected.country.name,selected.locality].filter(Boolean).join(' · '),'locality'));const label=element('label','Layout');label.htmlFor='layout';const control=element('select','');control.id='layout';for(const l of selected.layouts){const option=element('option',l.name);option.value=l.id;control.append(option);}control.value=requested;control.addEventListener('change',()=>select(selected.id,control.value));root.append(label,control);
 if(state==='loading')root.append(element('p',`Loading ${selected.layouts.find(l=>l.id===requested)?.name}…`,'loading'));
 if(state==='error'){root.append(element('p',error??'Data could not load','error'));const retry=element('button','Retry layout','button');retry.onclick=()=>select(selected.id,requested,false);root.append(retry);}
 if(state==='ready'&&layout){const m=layout.metadata;const statuses=element('div','','statuses');statuses.append(element('span',m.geometryStatus==='draft'?'Draft trace':'Reviewed trace','badge'),element('span',privateNotes.length?'Local timing reference':`Timing ${m.timingStatus}`,'badge timing'));root.append(statuses);const stats=element('div','','stats');const len=element('div','');len.append(element('strong',`${(m.lengthM/1000).toFixed(2)} km`),element('span','Approx. trace length'));const type=element('div','');type.append(element('strong',m.closed?'Closed circuit':'Point-to-point'),element('span','Route type'));stats.append(len,type);root.append(stats);const description=selected.layouts.find(l=>l.id===requested)?.description;if(description)root.append(element('p',description,'note'));for(const note of m.notes)root.append(element('p',note,'note'));if(!privateNotes.length&&m.timingStatus==='missing')root.append(element('p',m.timingMode==='shared'?'Start/finish position not yet verified':'Start and finish positions not yet verified','note'));for(const note of privateNotes)root.append(element('p',note,'note local-note'));for(const gate of layout.features.filter(f=>f.properties.role!=='trace')){const p=gate.properties;if('positionStatus'in p)root.append(element('p',`${p.role.replace('_',' / ')}: ${p.positionStatus}; ${p.endpointMethod}. ${p.positionNote}`,'note'));}
 const actions=element('div','','actions'),fitButton=element('button','Fit layout','button');fitButton.onclick=fit;const download=element('a','Download GeoJSON','button secondary');download.id='download';download.href=`${base}data/${layoutFile}`;download.download=`${selected.id}-${requested}.geojson`;actions.append(fitButton,download);root.append(actions);if(privateNotes.length)root.append(element('p','Download contains the reusable OSM trace. Local Racelogic timing is excluded.','download-note'));sourceLinks(root,selected);}}
async function select(id:string,requested?:string,push=true){const current=++sequence;abort?.abort();abort=new AbortController();const signal=abort.signal;selectedLayers.clearLayers();layout=undefined;layoutFile=undefined;message('Loading track…');const entry=catalogue.tracks.find(t=>t.id===id);if(!entry){clear();renderCatalogue();urlState(undefined,undefined,true);message('Unknown track. Choose one from the catalogue.');return;}
 document.querySelector('aside')!.classList.add('has-selection');track=undefined;get('selection').replaceChildren(element('p','Loading track…','loading'));
 try{const selected=validateTrack(await load(entry.file,signal));if(current!==sequence)return;track=selected;const valid=selected.layouts.some(l=>l.id===requested),layoutId=valid?requested!:selected.defaultLayoutId;if(push)urlState(id,layoutId);if(requested&&!valid){urlState(id,layoutId,true);message('Unknown layout. Showing the default layout.');}else message('');panel(selected,layoutId,'loading');get('map-name').textContent=`${selected.name} / ${selected.layouts.find(l=>l.id===layoutId)!.name}`;renderCatalogue();const file=entry.file.replace(/track\.json$/,'')+selected.layouts.find(l=>l.id===layoutId)!.file;const data=validateLayout(await load(file,signal),selected,layoutId);if(current!==sequence)return;layout=data;layoutFile=file;
 const timing=localTiming[`${id}/${layoutId}`],notes:string[]=[],privateLines:{role:string;coordinates:Position[];note:string}[]=[];
 if(timing){const trace=data.features[0].geometry.coordinates;const anchors=new Map();for(const g of timing.gates){const {anchor,coordinates}=localGate(g.point,trace);
 if(!coordinates){notes.push(`${g.role.replace('_',' / ')}: local GPS reference is ${anchor.displacementM.toFixed(0)} m from this layout. Gate hidden pending alignment review.`);continue;}
 anchors.set(g.role,anchor);privateLines.push({role:g.role,coordinates,note:`Local Racelogic reference. Estimated position; generated 25 m endpoints. ${anchor.displacementM.toFixed(1)} m from OSM trace.`});notes.push(`${g.role==='start_finish'?'Start / finish':g.role==='start'?'Start':'Finish'}: local Racelogic reference, ${anchor.displacementM.toFixed(1)} m from OSM. Estimated position; 25 m display endpoints.`);}
 if(timing.association==='proximity-only')notes.push('This private timing reference was matched by GPS proximity. Association with this course configuration is unverified.');
 notes.push('Private preview timing has not been independently verified for public redistribution.');
 if(layoutId==='nordschleife-btg'&&anchors.has('start')&&anchors.has('finish')){const trimmed=trimLoop(trace,anchors.get('start'),anchors.get('finish'));layout=structuredClone(data);layout.features[0].geometry.coordinates=trimmed;layout.metadata.closed=false;layout.metadata.lengthM=length(trimmed);layout.bbox=bounds(trimmed);notes.push('Preview trace trimmed at the projections of the local gates. Public download remains the full reusable supporting loop.');}
 }
 draw(layout,privateLines);panel(selected,layoutId,'ready',undefined,notes);message('Layout ready');
 }catch(e){if(current!==sequence||signal.aborted)return;selectedLayers.clearLayers();layout=undefined;layoutFile=undefined;message('Track data could not load.');if(track?.id===id)panel(track,requested??track.defaultLayoutId,'error',String(e));else{get('selection').replaceChildren(element('p',String(e),'error'));const retry=element('button','Retry track','button');retry.onclick=()=>select(id,requested,push);get('selection').append(retry);}}}
get('search').addEventListener('input',()=>renderCatalogue(true));get('country').addEventListener('change',()=>renderCatalogue(true));get('reset').onclick=()=>{get<HTMLInputElement>('search').value='';get<HTMLSelectElement>('country').value='';renderCatalogue(true);};
async function restore(){get<HTMLInputElement>('search').value='';get<HTMLSelectElement>('country').value='';const q=new URLSearchParams(location.search);if(q.has('track'))await select(q.get('track')!,q.get('layout')??undefined,false);else{clear();renderCatalogue();message('');}}
window.addEventListener('popstate',()=>void restore());
async function boot(){try{catalogue=indexSchema.parse(await load('index.json'));for(const c of [...new Map(catalogue.tracks.map(t=>[t.country.code,t.country])).values()].sort((a,b)=>a.name.localeCompare(b.name))){const option=element('option',c.name);option.value=c.code;get('country').append(option);}renderCatalogue();map.fitBounds(catalogue.tracks.map(t=>[t.location[1],t.location[0]] as L.LatLngTuple),{padding:[70,70],animate:false});await restore();}catch(e){message(`Catalogue unavailable: ${String(e)}`);const retry=element('button','Retry catalogue','button');retry.onclick=()=>{cache.delete('index.json');void boot();};get('venues').replaceChildren(retry);}}
new ResizeObserver(()=>map.invalidateSize()).observe(get('map'));

async function showCoverage(){
 try{
  const coverage=await load('world-coverage.json') as {countries:{country:{code:string;name:string};status:string;pending:number;groupsWithoutClosedCandidate?:number}[];candidates:{country:string;name?:string;status:string;reason?:string;sourceReference?:string}[]};
  const pending=coverage.candidates.filter(c=>c.status==='pending');
  const details=element('details','');details.className='coverage';details.append(element('summary',`Worldwide coverage · ${coverage.countries.length} countries and territories`));
  details.append(element('p','Coverage is in progress. Draft course candidates do not establish every venue, named layout, or travel direction. Karting and motocross are excluded.'));
  const table=element('table',''),head=element('tr','');head.append(element('th','Country'),element('th','Status'),element('th','Venues'),element('th','Pending candidates'));table.append(head);
  for(const c of coverage.countries){const row=element('tr','');row.append(element('td',c.country.name),element('td',c.status==='fetched'?'Fetched':c.status==='area-unavailable'?'Area unavailable':'Not fetched'),element('td',String(catalogue.tracks.filter(t=>t.country.code===c.country.code).length)),element('td',String(c.pending)));table.append(row);}
  details.append(table,element('p',`${pending.length} candidate groups or facilities await review. These can include out-of-scope facilities; this is not a count of missing road circuits. Open, short, excluded or unmapped traces need further inspection.`));
  const gaps=pending.filter(c=>c.name&&(c.sourceReference||c.reason?.includes('Named facility')||c.reason?.includes('Complex branching')));
  if(gaps.length){details.append(element('p','Known source gaps: '+gaps.map(c=>`${c.name} (${c.country})`).join(', ')+'.'));}
  const download=element('a','Download the full coverage inventory');download.href=`${base}data/world-coverage.json`;download.download='world-coverage.json';details.append(download);
  const report=element('a','Read the coverage report ↗');report.href='https://github.com/markthebault/open-racetrack-db/blob/main/Docs/08-worldwide-coverage.md';details.append(report);
  document.querySelector('footer')!.prepend(details);
 }catch{/* Older/public mirrors may not yet have the inventory. */}
}
void boot().then(showCoverage);
